steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
  - uses: actions/checkout@v2
  
  - name: Auto Minify
    uses: nizarmah/auto-minify@v2.1.1
    with: 
      # Optional. Directory that contains the files you want to minify. Defaults to current directory (.)
      directory: 'src' 
      # Optional. Directory that contains the minified files. Defaults to same directory
      # output: 'minified'
  
  # Auto commits minified files to the repository
  # Ignore it if you don't want to commit the files to the repository 
  - name: Auto committing minified files
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      repository: 'src'
      commit_message: 'Github Action: Auto Minified JS and CSS files'
      branch: ${{ github.ref }}
